### PR TITLE
Replace the year in the footer from hard coded to dynamically set

### PR DESCRIPTION
**Pull request by iSamBa**

### CODE REVIEW

**Comment by manuio** [comment]
@iSamBa Can you please sign you commit, fix the CI and resolve the conflicts?

**Comment by iSamBa** [comment]
@manuio everything is in order now

**Review by manuio — APPROVED** [review]
LGTM

**Comment by iSamBa** [comment]
@manuio can you please add a second reviewer ? 
in order to merge to master

**Review by dusanb94 — APPROVED** [review]

**Pull request merged**
